default_platform(:android)

platform :android do
  desc "Lane For Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production -t lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
          app: "1:389991233950:android:de23365829d6d53b0ebe8f",
          firebase_cli_token: "1//03341JZspxoA5CgYIARAAGAMSNwF-L9IrzhR-rlXCTYuqqAqIf2bS6oWJj5r0L6vqEe_S_Khvqxt1sLJncxl_9NB78OkggcadCik",
          android_artifact_type: "APK",
          android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
          testers: "ibtesamelmadhoun@gmail.com",
          release_notes: "Lots of amazing new features to test out!"
    )
  end
end
